### ISSUE TITLE
Functionalities not working in release mode

### ISSUE THREAD

**Issue by ttnisal** [adaptyteam/AdaptySDK-React-Native#102]
### Description

Hi, We can subscribe to products and see paywalls in debug mode, But when we are on release mode the paywalls and functionalities are not working. 

It gives the following error.

```
{"adaptyCode": 2006, "localized Description": "Failed to decode native...}
```

Adapty versions

```
 "@adapty/react-native-ui": "^2.0.0",
 "react-native-adapty": "^2.7.0"
```

### Version

2.7.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
    OS: macOS 14.1.1
    CPU: (8) x64 Apple M1
    Memory: 267.18 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
    Watchman: 2023.05.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /Users/ttn/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11090377
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
