### ISSUE TITLE
Adapty prompts to sign in with Apple ID

### ISSUE THREAD

**Issue by rt2zz** [adaptyteam/AdaptySDK-React-Native#110]
### Description

When I open my app, every time I get prompted to "Sign in with Apple ID".
I see this discussion about this happening in debug https://github.com/adaptyteam/AdaptySDK-React-Native/issues/60, but in my case this is happening in prod

### Version

v2.7.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
info Fetching system and libraries information...
System:
  OS: macOS 14.3
  CPU: (10) arm64 Apple M1 Max
  Memory: 1.49 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.17
    path: ~/.npm-global/bin/yarn
  npm:
    version: 9.7.2
    path: ~/dev/easy/ember/node_modules/.bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.4.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.73.4 is now available (your project is running on v0.73.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.4
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.4
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```
