### ISSUE TITLE
Code not executed after call the adapty.makePurchase method

### ISSUE THREAD

**Issue by KristianLentino99** [adaptyteam/AdaptySDK-React-Native#116]
### Description

Hi! first of all, congrats, your SDK is very easy to use and also your docs are quite good!
I have some really strange problems (both on IOS simulator and on a closed alpha on a real Android device). 
I've been following your tutorials and I have a method that is executed in an useEffect(() => ,[]) to fetch the paywall and the products, below an example:
```
try {
      const id = 'placement-id'
      const locale = 'en'

      const paywall = await adapty.getPaywall(id, locale)
      const products = await adapty.getPaywallProducts(paywall)
      setProducts(products)
    } catch (error) {
      console.error(error)
    }
```

this works fine and I'm able to retrieve my products. Then when I try to press the purchase button I have a method like this:
```
const handleOnSubmitCart = async () => {
    console.log(products[0])
    try {
      const response = await adapty.makePurchase(products[0])
      alert(response.customerUserId)
    } catch (error) {
      console.error(error)
    }
  }
```

and here I have really strange behavior. After the bottom sheet of IOS/Google closes, it seems I can't get any info, both on the catch or on the line after the `makePurchase` method.
I've also deployed a closed test on my google developer account but after paying the alert is never shown. 
Something that could be interesting is that after the bottom sheet closes, after more or less 1 second it gets reopen, even if I don't have any makePurchase on some hook to show it on mount of components, the only place where I have the makePurchase is the method which I use on the onPress event of the purchase button, like this:
```
<Button
  onPress={handleOnSubmitCart}
/>
```

One additional info that can be useful is that I'm running on expo 49 and I have this trick to make Adapty work at the moment: 
```
"plugins": [
            "expo-router", [
                "expo-build-properties",
                {
                    "android": {
                        "extraMavenRepos": [
                            "../../node_modules/react-native-adapty/lib/android/localMaven"
                        ]
                    }
                }
            ]
        ],
```

### Version

2.10.0

### What platforms are you seeing the problem on?

iOS, Android

### System info

```yml
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 87.06 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
