### ISSUE TITLE
TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.

### ISSUE THREAD

**Issue by SergiOnGit** [adaptyteam/AdaptySDK-React-Native#117]
### Description

App crashes on production and firebase logs this error:

`Fatal Exception: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
       at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:100)
       at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:70)
       at com.adapty.internal.di.Dependencies$init$1$1.<init>(Dependencies.kt:137)
       at com.adapty.internal.di.Dependencies$init$1.invoke(Dependencies.kt:137)
       at com.adapty.internal.di.Dependencies$init$1.invoke(Dependencies.kt:56)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$17.invoke(Dependencies.kt:287)
       at com.adapty.internal.di.Dependencies$init$17.invoke(Dependencies.kt:286)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$15.invoke(Dependencies.kt:272)
       at com.adapty.internal.di.Dependencies$init$15.invoke(Dependencies.kt:270)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$7.invoke(Dependencies.kt:217)
       at com.adapty.internal.di.Dependencies$init$7.invoke(Dependencies.kt:214)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$5.invoke(Dependencies.kt:200)
       at com.adapty.internal.di.Dependencies$init$5.invoke(Dependencies.kt:198)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$47.invoke(Dependencies.kt:446)
       at com.adapty.internal.di.Dependencies$init$47.invoke(Dependencies.kt:444)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.internal.di.Dependencies$init$48.invoke(Dependencies.kt:458)
       at com.adapty.internal.di.Dependencies$init$48.invoke(Dependencies.kt:456)
       at com.adapty.internal.di.DIObject.provide(DIObject.kt:19)
       at com.adapty.internal.di.Dependencies.injectInternal$default(Dependencies.java:35)
       at com.adapty.Adapty$special$$inlined$inject$adapty_release$default$1.invoke(Dependencies.kt:31)
       at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
       at com.adapty.Adapty.<clinit>(Adapty.kt:500)
       at com.adapty.Adapty.getAdaptyInternal(Adapty.kt:500)
       at com.adapty.Adapty.init(Adapty.kt:520)
       at com.adapty.Adapty.activate(Adapty.kt:64)
       at com.adapty.react.AdaptyCallHandler.handleActivate$lambda$1(AdaptyCallHandler.kt:64)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

At first, I could even build in production mode, I tried playing with proguard rules but no luck, then installed @adapty/react-native-ui lib and build went soccessfully, It is really bad that we have to install @adapty/react-native-ui even if we don't use it. Also docs doesn't say anything about it. After this I tried to open app, but crashed at startup.

### Version

v2.10.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: macOS 14.4.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 102.56 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/warlock/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/warlock/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
