### ISSUE TITLE
Xcode build error

### ISSUE THREAD

**Issue by mehmet-boz** [adaptyteam/AdaptySDK-React-Native#122]
### Description

Hi,

I get the following error when building react native app with Xcode 14.2. 

<img width="1076" alt="Screen Shot 2024-06-13 at 04 51 42" src="https://github.com/adaptyteam/AdaptySDK-React-Native/assets/57072664/725de26b-bcde-425d-a649-121f33ea1d04">

### Version

v2.11.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 12.7.5
  CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Memory: 347.91 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.0
    path: ~/node_modules/.bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/msiboz/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/msiboz/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.7
    wanted: 0.73.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
