### ISSUE TITLE
AdaptyPrice localizedString removes 2nd decimal if it is `0` in `.getPaywallProducts`

### ISSUE THREAD

**Issue by pkiler** [adaptyteam/AdaptySDK-React-Native#123]
### Description

Currently, requesting paywall products that have prices with their 2nd decimal as `0` seems to truncate this decimal.

Example response from `fetch/get-paywall-products` (calling `Adapty.getPaywallProducts`):
```
{
    "data": [
        {
            [...],
            "price": {
                "currency_code": "PEN",
                "amount": 19.9,
                "localized_string": "S/ 19.9",
                "currency_symbol": "S/"
            },
            "region_code": "PE",
        },
        {
            [...],
            "price": {
                "currency_symbol": "S/",
                "currency_code": "PEN",
                "amount": 39.9,
                "localized_string": "S/ 39.9"
            },
            "region_code": "PE"
        }
    ],
    "type": "Array<AdaptyPaywallProduct>"
}
```

But calling `Adapty.makePurchase` opens the native purchase window, with the price displayed with its 2 decimals as expected:

<img width="330" alt="image" src="https://github.com/adaptyteam/AdaptySDK-React-Native/assets/39346142/4c51c1e5-6535-4bd0-8ec5-77985c11df94">

Currency in the screenshot is PEN, but might be a general issue with other currencies.

### Version

2.10.1

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M3
  Memory: 153.58 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.06.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
