### ISSUE TITLE
Backup Rules Conflict with AppsFlyer SDK Causing Android Build Failure [Expo Managed Workflow]

### ISSUE THREAD

**Issue by troberts-28** [adaptyteam/AdaptySDK-React-Native#126]
### Description

EAS android builds fail when you have both the Adapty SDK and the AppsFlyer SDK installed because both define backup rules with different XML files:
`Manifest merger failed : Attribute application@fullBackupContent value=(@xml/adapty_backup_rules) from [io.adapty:android-sdk:2.11.3] AndroidManifest.xml:9:18-70 is also present at [com.appsflyer:af-android-sdk:6.14.0] AndroidManifest.xml:33:9-64 value=(@xml/appsflyer_backup_rules).`

```
"expo": "~51.0.26",
"react-native-adapty": "~2.11.1",
"react-native-appsflyer": "~6.14.3",
```

We are using the Expo managed workflow, so I have written a custom Expo plugin to circumvent the issue by preferentially using Adapty's backup rules over AppsFlyer's. I'm not sure of the effect of that though as I can't find the details of the backup rules in either of the repos. 

```
const { withAndroidManifest } = require("@expo/config-plugins");

const withCustomAndroidManifest = (config) => {
    return withAndroidManifest(config, async (config) => {
        const manifest = config.modResults.manifest;

        // ensure tools namespace is declared
        if (!manifest.$) {
            manifest.$ = {};
        }
        manifest.$["xmlns:tools"] = "http://schemas.android.com/tools";

        // add tools:replace to the application tag
        // this is required because both adapty and appsflyer define backup rules with different XML files
        if (manifest.application && manifest.application.length > 0) {
            const applicationTag = manifest.application[0];
            applicationTag["$"]["tools:replace"] = "android:fullBackupContent";
            applicationTag["$"]["android:fullBackupContent"] =
                "@xml/adapty_backup_rules"; // Or '@xml/appsflyer_backup_rules' (can only use one...)
        }

        return config;
    });
};

module.exports = withCustomAndroidManifest;
```

### Version

v2.11.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
  Memory: 1.83 GB / 15.01 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 21.1.0
    path: ~/.nvm/versions/node/v21.1.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v21.1.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v21.1.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /home/troberts28/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```
