### ISSUE TITLE
Is there a way to present the view and not have it underneath the status bar?

### ISSUE THREAD

**Issue by rennard** [adaptyteam/AdaptySDK-React-Native#127]
### Description

I'm using SafeAreaView in the rest of my application and it all works fine, but if I use the legacy builder an `view.present()` then it doesn't respect the SafeAreaView and renders underneath the statusbar. Is this an inherent limitation of the SDK or am I missing something? Thanks!

### System info

```yml
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 147.63 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.8.0
    path: ~/.nvm/versions/node/v18.8.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.8.0/bin/yarn
  npm:
    version: 8.18.0
    path: ~/.nvm/versions/node/v18.8.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
