### ISSUE TITLE
onPurchaseCompleted is never called on Android expo

### ISSUE THREAD

**Issue by rennard** [adaptyteam/AdaptySDK-React-Native#128]
### Description

onPurchaseCompleted is never called on successful purchase of the subscription, hence the paywall is never dismissed and the adaptyProfile is never updated. The subscription is active, as my google play subscriptions shows.
This is the case both if I override the listener and if I leave it as the default. I cannot get the adaptyprofile to update in any way

### Version

v2.11.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 73.84 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.8.0
    path: ~/.nvm/versions/node/v18.8.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.8.0/bin/yarn
  npm:
    version: 8.18.0
    path: ~/.nvm/versions/node/v18.8.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
