### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rafakwolf** [adaptyteam/AdaptySDK-React-Native#133]
### Description

Command used:
`eas build --platform android --profile development --local`

Error:
```
[RUN_GRADLEW]   Attribute application@fullBackupContent value=(@xml/secure_store_backup_rules) from AndroidManifest.xml:19:202-260
[RUN_GRADLEW]   is also present at [io.adapty:android-sdk:3.1.1] AndroidManifest.xml:9:18-70 value=(@xml/adapty_backup_rules).
[RUN_GRADLEW]   Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:6:5-162 to override.
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:processDebugMainManifest'.
[RUN_GRADLEW] > Manifest merger failed : Attribute application@fullBackupContent value=(@xml/secure_store_backup_rules) from AndroidManifest.xml:19:202-260
[RUN_GRADLEW]           is also present at [io.adapty:android-sdk:3.1.1] AndroidManifest.xml:9:18-70 value=(@xml/adapty_backup_rules).
[RUN_GRADLEW]           Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:6:5-162 to override.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 20s
```

### Version

v3.1.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
EAS CLI 14.4.1 environment info:
    System:
      OS: macOS 14.7.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm
    Utilities:
      Git: 2.39.3 - /usr/bin/git
    npmPackages:
      expo: ~52.0.26 => 52.0.26
      expo-dev-client: ~5.0.9 => 5.0.9
      expo-updates: ~0.26.13 => 0.26.13
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.6 => 0.76.6
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 14.4.1
    Project workflow: managed
```
