### ISSUE TITLE
Adapty: setFallbackPaywalls Requires iOS Fallback Even When Only Android is Used

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptySDK-React-Native#136]
### Description

I’m encountering an issue with the react-native-adapty package when setting the fallback location for paywalls. My project is Android-only, but when I don’t specify an iOS fallback, I receive the following error:

`fallback initialization error [TypeError: Cannot read property 'fileName' of undefined]`

This happens when I define my paywallsLocation object without an iOS fallback, as shown below:

Not Working Code:

```
const paywallsLocation = {
  ios: {
    // fileName: 'ios_fallback.json',
  },
  android: {
    relativeAssetPath: 'android_fallback.json',
  },
};
```

However, if I include an iOS fallback, even though my app does not run on iOS, the issue is resolved:

Working Code:

```
const paywallsLocation = {
  ios: {
    fileName: 'ios_fallback.json',
  },
  android: {
    relativeAssetPath: 'android_fallback.json',
  },
};
```

Questions:
	1.	Why is the iOS fallback required even when the app is only running on Android?
	2.	Is the Android fallback using the iOS fallback internally?
	3.	Shouldn’t Adapty ignore the iOS fallback entirely if the app is Android-only?

Versions Used:
	•	react-native: 0.75.4
	•	react-native-adapty: ^3.3.0

Would appreciate any insights into why this behavior occurs and whether it is expected. Thanks!

Full code:

```
const paywallsLocation = {
  ios: {
    fileName: 'ios_fallback.json',
  },
  android: {
    //if the file is located in 'android/app/src/main/assets/'
    relativeAssetPath: 'android_fallback.json',
  },
};

  useEffect(() => {
    async function init() {
      try {
        let deviceJSON = {};
        deviceJSON.uniqueId = await getUniqueId();
        // console.info('[ADAPTY] Activating Adapty SDK....', deviceJSON.uniqueId);
        await adapty.activate('public_live_xxxx', {
          observerMode: false,
          customerUserId: deviceJSON.uniqueId,
          logLevel: 'verbose',
          ipAddressCollectionDisabled: false,
        });
      } catch (error) {
        console.log('[ADAPTY] Error activating Adapty SDK', error);
      }
    }
    async function fetch() {
      try {
        console.log('fetching');
        await init();

        await adapty.setFallbackPaywalls(paywallsLocation);
        setIsAdaptyInitialized(true);
      } catch (error) {
        console.log('fallback initalization error', error);
      }
    }
    fetch();
    return () => {
      // Unsubscribe from adapty events
      // console.log('[ADAPTY] Unsubscribing from adapty events');
      adapty.removeAllListeners();
    };
  }, []);
```

### Version

v3.3.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: macOS 15.2
  CPU: (8) arm64 Apple M1
  Memory: 260.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.12816248
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
