### ISSUE TITLE
PurchaseResult.profile.accessLevels Changed to paid_access_levels in New Version

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptySDK-React-Native#137]
### Description

After updating to the latest version of react-native-adapty, I noticed that the structure of purchaseResult has changed. Previously, after a successful purchase, the response followed the format documented in the official Adapty documentation and previous versions:

Old Version (Documented & Previously Working Code):

```
try {
    const purchaseResult = await adapty.makePurchase(product);
    switch (purchaseResult.type) {
      case 'success':
        const isSubscribed = purchaseResult.profile?.accessLevels['YOUR_ACCESS_LEVEL']?.isActive;

        if (isSubscribed) {
          // Grant access to the paid features
        }
        break;
      case 'user_cancelled':
        // Handle the case where the user canceled the purchase
        break;
      case 'pending':
        // Handle deferred purchases (e.g., the user will pay offline with cash)
        break;
    }
} catch (error) {
    // Handle the error
}
```

However, in the new version, purchaseResult.profile.accessLevels no longer exists, and the structure has changed to purchaseResult.profile.paid_access_levels. Now, I have to access the subscription status like this:

New Version (Current Behavior):

`const isSubscribed = purchaseResult.profile?.paid_access_levels['premium']?.is_active;`

New Response Format:

```
{
    "profile": {
        "paid_access_levels": {
            "premium": {
                "activated_at": "2025-02-10T12:58:12.815000+0000",
                "expires_at": "2025-02-10T13:58:11.900000+0000",
                "id": "premium",
                "is_active": true,
                "is_in_grace_period": false,
                "is_lifetime": false,
                "is_refund": false,
                "renewed_at": "2025-02-10T13:28:11.900000+0000",
                "store": "play_store",
                "vendor_product_id": "com.xxxx",
                "will_renew": true
            }
        },
        "custom_attributes": {},
        "customer_user_id": "xxxxxx",
        "is_test_user": false,
        "non_subscriptions": {},
        "segment_hash": "not implemented",
        "timestamp": -1
    },
    "type": "success"
}
```

Questions:
	1.	Was this change intentional, or is it a bug?
	•	If it’s a mistake, fixing it could impact production users who rely on the old structure to check subscriptions.
	2.	Is this the final structure, or will an update be released to revert it?
	3.	If an update is planned, do you have a backup plan to avoid breaking existing implementations in production?

This change is significant and affects subscription handling in production, so I’d appreciate clarification. Thanks!

### System info

```yml
System:
  OS: macOS 15.2
  CPU: (8) arm64 Apple M1
  Memory: 237.13 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.12816248
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
