### ISSUE TITLE
PurchaseResult.profile.accessLevels Missing Suddenly – Production Users Unable to Access Premium

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptySDK-React-Native#138]
### Description

We have been using the following versions of Adapty in production for a long time without any issues:
```
	•	@adapty/react-native-ui: ^3.0.1
	•	react-native-adapty: ^3.0.1
```

However, without updating these dependencies, users who have made a successful purchase are suddenly unable to access premium features. It appears that the purchaseResult response structure has changed unexpectedly.

Questions & Urgent Concerns:
	1.	This issue happened without updating Adapty—was there a server-side change that caused this?
	2.	If this is an unintentional change, will there be a fix or rollback?
	3.	If a fix is required, how can we prevent breaking the experience for current users?

Since this is affecting paying users in production, we need an urgent resolution.

### Version

v3.0.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: macOS 15.2
  CPU: (8) arm64 Apple M1
  Memory: 260.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23726.103.2422.12816248
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
