### ISSUE TITLE
Critical Bug: Crash in EventsManager on App Launch

### ISSUE THREAD

**Issue by enestatli** [adaptyteam/AdaptySDK-React-Native#139]
### Description

I am seeing crashes related to EventsManager in Crashlytics, but I haven’t been able to reproduce them myself. The crash occurs on app launch, I believe making this an urgent issue that needs to be fixed immediately.

I am using react-native-adapty with Adapty in observerMode. The crash happens across different iOS versions and device models.

**Crash Log (Crashlytics)**
```
EventsManager.trackEvent(_:completion:)
EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)


EventsManager.swift:72

Crashed: Adapty.SDK.SendEvents
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000054
          Crashed: Adapty.SDK.SendEvents
0  libdispatch.dylib              0x3cfe0 dispatch_async$VARIANT$armv81 + 148
1  libswiftDispatch.dylib         0x1b94 _swift_dispatch_async + 48
2  libswiftDispatch.dylib         0x24ec OS_dispatch_queue.async(group:qos:flags:execute:) + 152
3  {appname}                      0x138d20 EventsManager.trackEvent(_:completion:) + 72 (EventsManager.swift:72)
4  {appname}                      0x2b6720 specialized HTTPSession.perform<A>(_:logName:logStamp:logParams:_:) + 4368312096
5  {appname}                      0x2b6430 specialized HTTPSession.perform<A>(_:logName:logStamp:logParams:_:) + 4368311344
6  {appname}                      0x13b444 specialized EventsManager.sendEvents(_:completion:) + 173 (EventsManager.swift:173)
7  {appname}                      0x139650 closure #1 in EventsManager.needSendEvents() + 106 (EventsManager.swift:106)
8  {appname}                      0x166ec thunk for @escaping @callee_guaranteed @Sendable () -> () + 4365559532 (<compiler-generated>:4365559532)
9  libdispatch.dylib              0x637a8 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x64780 _dispatch_client_callout + 16
11 libdispatch.dylib              0x3f6fc _dispatch_lane_serial_drain$VARIANT$armv81 + 600
12 libdispatch.dylib              0x401b0 _dispatch_lane_invoke$VARIANT$armv81 + 380
13 libdispatch.dylib              0x49f14 _dispatch_workloop_worker_thread + 608
14 libsystem_pthread.dylib        0x1bd0 _pthread_wqthread + 284
15 libsystem_pthread.dylib        0x1720 start_wqthread + 8
```

**Devices & iOS Versions Affected**
This crash happens on multiple devices and iOS versions:

- iPhone X – iOS 16.7.10
- iPhone XS – iOS 18.0.1
- iPhone 11 Pro – iOS 18.1.1
- iPhone 15 – iOS 18.3.0
- iPhone 14 – iOS 18.1.1
- iPhone 12 Pro – iOS 16.6.1

### Version

v3.1.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M2
  Memory: 114.97 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.11.0
    path: ~/.nvm/versions/node/v22.11.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.11.0/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/enestatli/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "33"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 35.0.0
    System Images:
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/enestatli/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.11
    wanted: 0.73.11
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
