### ISSUE TITLE
Compliation error with xcode 16.3

### ISSUE THREAD

**Issue by maxoschepkov** [adaptyteam/AdaptySDK-React-Native#141]
### Description

With a new version of xcode compilation fails with:
```
❌  (ios/Pods/Adapty/Sources/Backend.HTTPSession/Codable/CodingUserInfoСontainer.swift:15:1)

  13 | }
  14 | 
> 15 | extension JSONDecoder: CodingUserInfoСontainer {}
     | ^ type 'JSONDecoder' does not conform to protocol 'CodingUserInfoСontainer'
  16 | extension JSONEncoder: CodingUserInfoСontainer {}
  17 | 


❌  (ios/Pods/Adapty/Sources/Backend.HTTPSession/Codable/CodingUserInfoСontainer.swift:16:1)

  14 | 
  15 | extension JSONDecoder: CodingUserInfoСontainer {}
> 16 | extension JSONEncoder: CodingUserInfoСontainer {}
     | ^ type 'JSONEncoder' does not conform to protocol 'CodingUserInfoСontainer'
  17 | 
```

### Version

v3.3.1

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 15.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 1.24 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: ~/.nvm/versions/node/v20.18.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.18.1/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.1/bin/npm
  Watchman:
    version: 2025.02.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.4
      - iOS 18.4
      - macOS 15.4
      - tvOS 18.4
      - visionOS 2.4
      - watchOS 11.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.3/16E140
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: ^18.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.7
    wanted: 0.76.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
