### ISSUE TITLE
[iOS] Local build fails at Adapty pod install

### ISSUE THREAD

**Issue by RayanMoarkech** [adaptyteam/AdaptySDK-React-Native#142]
### Description

```
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     react-native-adapty-sdk (from ../node_modules/react-native-adapty) was resolved to 3.4.0, which depends on
[INSTALL_PODS]       AdaptyUI (= 3.4.2)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: AdaptyUI (= 3.4.2).
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with pod repo update or with pod install --repo-update.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
```

### Version

v3.4.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
npx expo-env-info

  expo-env-info 1.2.2 environment info:
    System:
      OS: macOS 15.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 11.2.0 - /usr/local/bin/npm
      Watchman: 2025.03.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/rayanmoarkech/.rvm/gems/ruby-3.4.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.4, iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4
      Android SDK:
        API Levels: 29, 30, 32, 33, 34, 35
        Build Tools: 29.0.3, 30.0.2, 30.0.3, 32.0.0, 33.0.0, 34.0.0
        System Images: android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.3 AI-243.24978.46.2431.13208083
      Xcode: 16.3/16E140 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.42 => 52.0.42 
      expo-router: ~4.0.20 => 4.0.20 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.9 => 0.76.9 
    npmGlobalPackages:
      eas-cli: 16.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```
