### ISSUE TITLE
Conflict with expo-secure-store

### ISSUE THREAD

**Issue by rolandschuetz** [adaptyteam/AdaptySDK-React-Native#143]
### Description

I want to include adapty to my app, but adding the plugin causes my Expo managed workflow to fail on Android with this error:
```
Manifest merger failed : Attribute application@fullBackupContent value=(@xml/secure_store_backup_rules) from AndroidManifest.xml:24:248-306
	is also present at [io.adapty:android-sdk:3.4.0] AndroidManifest.xml:9:18-70 value=(@xml/adapty_backup_rules).
	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:24:3-54:17 to override.
Use code with caution.
```

Seems that both expo-secure-store and the react-native-adapty library are trying to define the android:fullBackupContent attribute within the <application> tag of the final AndroidManifest.xml. 
expo-secure-store sets it to @xml/secure_store_backup_rules.
react-native-adapty sets it to @xml/adapty_backup_rules.

What should I do?

### System info

```yml
`npx react-native`does not work. 

Here are the probably important dependencies:

    "expo": "~52.0.20",
    "expo-secure-store": "~14.0.0",
    "react-native-adapty": "^3.4.0",
```
