### ISSUE TITLE
Error: #3001 (wrongParam): AdaptyPaywall.viewConfiguration is nil

### ISSUE THREAD

**Issue by salihgun** [adaptyteam/AdaptySDK-React-Native#147]
### Description

```
    const paywall = await adapty.getPaywall('onboardingtest');
      console.log('paywall', paywall)
      const view = await createPaywallView(paywall);
      await view.present();
```

```
{
    "abTestName": "onboardingtest",
    "audienceName": "All Users",
    "placementId": "onboardingtest",
    "instanceIdentity": "4e92e388-f031-4dcb-af42-af00468c029f",
    "name": "onboardingtest",
    "products": [
        {
            "vendorId": "xxxx",
            "adaptyId": "xxxxx",
            "ios": {},
            "android": {}
        }
    ],
    "remoteConfig": {
        "data": {
            "button_color": "red"
        },
        "lang": "en",
        "dataString": "{\"button_color\":\"red\"}"
    },
    "revision": 1,
    "variationId": "fa8f4dd6-33b6-4a20-b4d0-cd1672927df2",
    "version": 1749154717291,
    "hasViewConfiguration": false
}
```

Onboarding.tsx:47 Error getting paywall: Error: #3001 (wrongParam): AdaptyPaywall.viewConfiguration is nil

 "react-native": "0.79.2",
  "react-native-adapty": "^3.6.1",

### Version

v3.6.1

### What platforms are you seeing the problem on?

iOS

### System info

```yml
info Fetching system and libraries information...
System:
  OS: macOS 15.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 111.81 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: 18.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.2
    wanted: 0.79.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
