### ISSUE TITLE
Error: #3005 (activateOnceError): You need to be activate Adapty once

### ISSUE THREAD

**Issue by code-with-shahzad** [adaptyteam/AdaptySDK-React-Native#148]
### Description

I am using using adapt in my react native app not sure why I am getting this error 
"Error: #3005 (activateOnceError): You need to be activate Adapty once"
I tried many methods but still it is same not sure what I am doing wrong.

```
import { LogLevel, adapty } from "react-native-adapty";

const initializeAdapty = () => {
  const options = {
    logLevel: LogLevel.ERROR,
    observerMode: false,
    activateUi: false,
  };

  try {
    adapty.activate("public_live_oXBTDFb1.kcS33O8seFRcH1HpZ1ye", options);
  } catch (error) {
    console.error("[Adapty] Initialization failed:", error);
  }
};

export { adapty, initializeAdapty };
```

even I tried without any options 
`adapty.activate(API_KEY);`

app.tsx
`initializeAdapty();`
or
```
adapty.activate(API_KEY);

const App = () => {}
```

usage
```
import { adapty } from "react-native-adapty";
or
import { adapty } from "../config/adapty";


export const getPaywall = async () => {
  return await adapty.getPaywall("premium").catch((err) => console.warn(err));
};
```

### Version

v3.6.1

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 15.5
  CPU: (10) arm64 Apple M4
  Memory: 122.55 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.15.1
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2025.04.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.4
      - iOS 18.4
      - macOS 15.4
      - tvOS 18.4
      - visionOS 2.4
      - watchOS 11.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.3/16E140
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: 18.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.2
    wanted: 0.79.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
