### ISSUE TITLE
android fetching products failed

### ISSUE THREAD

**Issue by salihgun** [adaptyteam/AdaptySDK-React-Native#149]
### Description

I added products on play console, everything works well on iOS but on Android I present paywall successfully but can't see the products.  Here the logs of a paywall which has products on android, Im confused.
`
{
    "abTestName": "App Open",
    "audienceName": "All Users",
    "placementId": "app_open",
    "instanceIdentity": "c6ce9184-df36-439b-937e-764e354a593a",
    "name": "App Open",
    "products": [
        {
            "vendorId": "tts.weekly",
            "adaptyId": "99e72844-0fe3-4469-bc44-66e2ad73ef44",
            "ios": {},
            "android": {
                "basePlanId": "tts-weekly-premium"
            }
        },
        {
            "vendorId": "tts.annually_3_trial",
            "adaptyId": "3979a0f9-4f13-4f97-ba06-790fc8964348",
            "ios": {},
            "android": {
                "basePlanId": "tts-annually-3-trial-premium"
            }
        }
    ],
    "revision": 1,
    "variationId": "1b133a02-7ab3-49ab-8016-5eb7f29e558c",
    "version": 1750158116022,
    "paywallBuilder": {
        "id": "fbee9154-193b-4d70-8754-f90baf16733c",
        "lang": "en"
    },
    "hasViewConfiguration": true
}`

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/912db6a6-02d4-4522-beec-9ece8e77cde5" />

### Version

v^3.6.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
System:
  OS: macOS 15.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 53.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 18.0.0
    wanted: 18.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.2
    wanted: 0.79.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
