### ISSUE TITLE
java.lang.NullPointerException at com.adapty.internal.crossplatform.ui.AdaptyUiActivity

### ISSUE THREAD

**Issue by BaloghTamas** [adaptyteam/AdaptySDK-React-Native#157]
### Description

We see the following crash in our report.

Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3846)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4022)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2336)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8653)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by java.lang.NullPointerException:
  at com.adapty.internal.crossplatform.ui.AdaptyUiActivity$special$$inlined$inject$crossplatform_release$default$1.invoke (Dependencies.kt:73)
  at kotlin.UnsafeLazyImpl.getValue (Lazy.kt:81)
  at com.adapty.internal.crossplatform.ui.AdaptyUiActivity.getPaywallUiManager (AdaptyUiActivity.kt:32)
  at com.adapty.internal.crossplatform.ui.AdaptyUiActivity.onCreate (AdaptyUiActivity.kt:44)
  at android.app.Activity.performCreate (Activity.java:8207)
  at android.app.Activity.performCreate (Activity.java:8191)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3819)

### Version

3.4.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
info Fetching system and libraries information...
System:
  OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
  CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Memory: 42.21 GB / 62.70 GB
  Shell:
    version: "5.9"
    path: /usr/bin/zsh
Binaries:
  Node:
    version: 22.12.0
    path: ~/.nvm/versions/node/v22.12.0/bin/node
  Yarn:
    version: 1.22.5
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.12.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
      - "36"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
      - 36.0.0
    System Images:
      - android-23 | Intel x86 Atom_64
      - android-24 | Intel x86 Atom_64
      - android-24 | Google APIs Intel x86 Atom
      - android-24 | Google APIs Intel x86 Atom_64
      - android-25 | Intel x86 Atom_64
      - android-26 | Google APIs Intel x86 Atom_64
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-28 | Google Play Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-31 | Google APIs Intel x86 Atom_64
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play Intel x86_64 Atom
      - android-35 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.1
    path: /usr/lib/jvm/temurin-jdk-17/jdk-17.0.1+12/bin/javac
  Ruby:
    version: 3.1.2
    path: /home/bata/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.3
    wanted: 16.0.3
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.79.2
    wanted: 0.79.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.80.0 is now available (your project is running on v0.79.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.80.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.79.2&to=0.80.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=linux".
```
