### ISSUE TITLE
Calling adapty.activate in a simulator triggers the login request

### ISSUE THREAD

**Issue by amberv0** [adaptyteam/AdaptySDK-React-Native#60]
### Description

Hey!
I just updated from v1 to v2.4.2 and I see the login screen pop up as soon as I call `adapty.activate(config.ADAPTY_PUBLIC_KEY)`. 

As in a simulator I would never be logged in, it's very annoying. Not sure about real users, but it's worrying. Never had this problem with v1.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/11645756/226716907-e8012101-6051-485a-a309-2f3734442e2e.png">

### Version

v2.4.2

### What platforms are you seeing the problem on?

iOS

### System info

```yml
IDEs:
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
 
npmPackages:
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3
```
