### ISSUE TITLE
Wrong Typescript type for ErrorCode

### ISSUE THREAD

**Issue by kamiranoff** [adaptyteam/AdaptySDK-React-Native#62]
### Description

I console log an Adapty error and get this object:

```
{
    "adaptyCode": 1006,
    "localizedDescription": "Product purchase failed"
    "message": "#undefined (1006): Product purchase failed"
}
```

`adaptyCode` seems to be one of the keys of `const ErrorCode` declared in `node_modules/react-native-adapty/lib/dist/types/error.d.ts` 

But the `type` is defined as such :
```
export declare type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
```

which, according to my editor, translates to (see screenshot):

![Screenshot 2023-03-28 at 11 10 28](https://user-images.githubusercontent.com/5861100/228203922-c893cc37-f703-4c32-8f13-c09f69e2f368.png)

It seems to me that the correct type should be:
```
export declare type ErrorCode = keyof typeof ErrorCode;
``` 

Is that correct? 

### Version

v2.4.2

### What platforms are you seeing the problem on?

iOS, Android

### System info

```yml
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 157.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/kamiranoff/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Also on a side note, I try to omit the error when a user discards the IOS modal without completing a purchase. Is 1006 the proper error code for that? I don't see any specific error like `user cancelled` or something like this. I can also open another issue if you would like.
