### ISSUE TITLE
Pressing Cancel on Payment sheet on ios returns ErrorCode 1006

### ISSUE THREAD

**Issue by kamiranoff** [adaptyteam/AdaptySDK-React-Native#63]
### Description

The error returned on Pressing cancel on the PaymentSheet on ios looks like this:

```
adaptyCode: 1006
jsEngine: "hermes"
localizedDescription: "Product purchase failed"
message: "#1006 (productPurchaseFailed): Product purchase failed"
stack: "Error: #1006 (productPurchaseFailed): Product purchase failed
```

This is not wrong but, in my opinion, it would be good to differentiate genuine errors from active cancellations from the user.

The native log contains the original error code for cancellation [SKErrorDomain Code=2](https://developer.apple.com/documentation/storekit/skerror/code/paymentcancelled) but then gets lost ultimately in `SKManagerError.swift` I believe

```
[Adapty JS] — ERROR: : <-- Native SDK replied with error
	error="#1006 (productPurchaseFailed): Product purchase failed"
	nativeError="{\n  \"code\": \"adapty_native_error\",\n  \"message\": \"{\\\"adapty_code\\\":1006,\\\"message\\\":\\\"Product purchase failed\\\",\\\"detail\\\":\\\"StoreKitManagerError.productPurchaseFailed([2.4.1]: Adapty\\\\/SKQueueManager+MakePurchase.swift#46, Error Domain=SKErrorDomain Code=2 \\\\\\\"(null)\\\\\\\" UserInfo={NSUnderlyingError=0x6000017398c0 {Error Domain=ASDErrorDomain Code=907 \\\\\\\"Unhandled exception\\\\\\\" UserInfo={NSUnderlyingError=0x600001736670 {Error Domain=AMSErrorDomain Code=6 \\\\\\\"Payment Sheet Failed\\\\\\\" UserInfo={NSLocalizedDescription=Payment Sheet Failed,
```

Would it be possible to differentiate the User Cancelled error with `adaptyCode` to deal with those accordingly? 

I have not implemented Android yet, and not sure what the behaviour is there.

### Version

v2.4.3

### What platforms are you seeing the problem on?

iOS

### System info

```yml
(I ran `npx react-native info` and not `npx react-native` as suggested by the template as it does not seem to be a valid command )

System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/kamiranoff/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
