### ISSUE TITLE
waitUntilActive + lockMethodsUntilReady not locking method threads 

### ISSUE THREAD

**Issue by mlaythe** [adaptyteam/AdaptySDK-React-Native#64]
### Description

Initializing adapty in a `useEffect` at the main app level
```
useEffect(() => {
  console.log('before adapty activate call')

  adapty.activate(adaptyKey, {
    logLevel: LogLevel.ERROR,
    lockMethodsUntilReady: true
  }).then(() => { console.log('adapty is activated') });

}, [adaptyKey]);
```

Some code to fetch an adapty paywall
```
export const fetchAdaptyPaywall = async (
  paywallName: PaywallNameType
): Promise<AdaptyPaywall | undefined> => {
  try {
    console.log('fetch paywall')
    await adapty.waitUntilActive();
    console.log('after waitUntilActive')
    const paywall = await adapty.getPaywall(paywallName);
    console.log('right after getPaywall')

    return paywall;
  } catch (error) {
    console.log('error inside fetchAdaptyPaywall', error)
  }
};
```

I'm currently trying to setup deeplinking into a paywall screen where it immediately calls `fetchAdaptyPaywall` however it throws exceptions saying adapty isn't initialized.

Am I using `waitUntilActive` incorrectly?

Here are some console logs
```
 LOG  fetch paywall
 LOG  before adapty activate call
 LOG  error inside fetchAdaptyPaywall [Error: #2002 (notActivated): The Adapty is not activated]
 LOG  adapty is activated
```

In your guys code I notice that `activationPromise` is only set inside the `activate` call, so if `waitUntilActive` is called prior to  `activate` it'll just throw an error since `activationPromise` isn't set. I found that to be unexpected behavior. 

Possible to lock all method calls regardless if `activate` was called prior or not?

### Version

v2.4.3

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
    OS: macOS 13.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 23.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/michael/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not FoundSystem:
    OS: macOS 13.2.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 23.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/michael/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```
