### ISSUE TITLE
"Failed to deserialize a native error message" on SDK initialization

### ISSUE THREAD

**Issue by canpoyrazoglu** [adaptyteam/AdaptySDK-React-Native#76]
### Description

I'm trying to initialize the SDK:

```
   adapty.activate(env.adaptySdkKey, { customerUserId }).then(async () => {
          ...
        });
```
My `env.adaptySdkKey` and `customerUserId` are set and valid. However when I'm initing I get a console warning:

`Failed to deserialize a native error message`

Digging down further into React Native bridge and putting a breakpoint there reveals the following details with the provided error data object:

```
{
  "code":"adapty_native_error",
  "message":"Argument 'id' was not passed to a native module.",
  "domain":"RCTErrorDomain",
  [...]
}
```

What am I doing wrong? (Tried iOS-only. I currently can't test Android so I don't know it happens on Android too or not)

### Version

2.4.2

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 178.22 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
