### ISSUE TITLE
Issue with remoteConfigs (localization + legacy) for updating users

### ISSUE THREAD

**Issue by snake302** [adaptyteam/AdaptySDK-React-Native#77]
### Description

Hello! We are currently investigating an issue, which is as follows:

We have a paywall named test_1, which contains two identical remoteConfigs - one in With Localization (en default) and the other in Without Localization. The configs are 100% identical and valid.

We have another paywall named test_2, which contains one remoteConfig in With Localization (en default), identical to the two configs from test_1.

The problem is:

We have the first version of the app 1.0.0 (using "react-native-adapty": "2.2.1"), which works only with paywall test_1 and Legacy Without Localization Remote Config. Upon updating the app to version 1.0.1 (which uses "react-native-adapty": "2.4.6") and requesting paywall test_1 (getPaywall, locale en) - the remote config does not come through. 
However, when requesting paywall test_2 (getPaywall, locale en) - the remote config comes through, and everything works.

If we install version 1.0.1 from scratch and request paywall test_1 (getPaywall, locale en) - the remote config comes through.

It seems that there is some issue with the paywall that was on the legacy remote config and the app transitioning from an older version of React Native to a newer one, where the paywall now utilizes a remote config with locale.

### Version

v2.4.6

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 49.70 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /var/folders/vg/cv8q3tzj1hdfjfd7t0v26vd80000gn/T/yarn--1686898500765-0.8989131801691097/node
    Yarn: 1.22.17 - /var/folders/vg/cv8q3tzj1hdfjfd7t0v26vd80000gn/T/yarn--1686898500765-0.8989131801691097/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
```
