### ISSUE TITLE
Argument 'product' was not passed to a native module.

### ISSUE THREAD

**Issue by canpoyrazoglu** [adaptyteam/AdaptySDK-React-Native#81]
### Description

I'm trying to make a purchase by calling ` await adapty.makePurchase(product);` where `product` is:

![Screenshot 2023-07-11 at 10 58 28](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/4348413/35084d49-56a8-43a8-8e0f-be73d5d688b6)

(details redacted for privacy)

I'm getting the "Failed to deserialize a native error message" message again. I've also raised another issue in the past (https://github.com/adaptyteam/AdaptySDK-React-Native/issues/76) which was being raised the same way but the underlying error is different here (it was me passing an object instead of a string, which is not the case here).

I'm getting "Argument 'product' was not passed to a native module." but I'm calling `adapty.makePurchase` with a `product` object as seen above, which is a clear and valid `product` object.

More weirdly, I have another paywall which uses the _exact_ same code path just with a different `product` (but has the same shape/fields), it works perfectly.

What might be going on?

### Version

v2.4.2

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.34 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
