### ISSUE TITLE
Purchase Failed in sandbox with Unknown Error

### ISSUE THREAD

**Issue by samuelzxu** [adaptyteam/AdaptySDK-React-Native#88]
### Description

I was attempting to make a purchase in the sandbox but was greeted with an unknown error:

[Error: #0 (unknown): Product purchase failed]
```
  const handlePurchase = async () => {
    try {
      const id = 'pairsessentials';
      const locale = 'en';

      const paywall = await adapty.getPaywall(id, locale);
      const products = await adapty.getPaywallProducts(paywall);
      const profile = await adapty.makePurchase(products[0]);
      console.log(profile);
      } catch (error) {
        console.log(error);
      }
    }
```

### Version

^2.6.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 55.05 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
