### ISSUE TITLE
v2.6.0 requires @adapty/react-native-ui v1.1.0 which is not released yet

### ISSUE THREAD

**Issue by rikur** [adaptyteam/AdaptySDK-React-Native#89]
### Description

```
!] CocoaPods could not find compatible versions for pod "Adapty":
  In snapshot (Podfile.lock):
    Adapty (= 2.4.5, >= 2.4.5, ~> 2.4.0)

  In Podfile:
    adapty-react-native-ui (from `../node_modules/@adapty/react-native-ui`) was resolved to 1.0.3, which depends on
      Adapty (= 2.4.5)

    react-native-adapty (from `../node_modules/react-native-adapty`) was resolved to 2.6.0, which depends on
      Adapty (= 2.6.3)

```

```
Couldn't find any versions for "@adapty/react-native-ui" that matches "^1.1.0"
? Please choose a version of "@adapty/react-native-ui" from this list:
❯ 1.0.4-rc.1
  1.0.3
  1.0.3-canary.2
  1.0.3-canary.1
  1.0.2
  1.0.1
  1.0.0-beta.2
  1.0.0-beta.1
```

### Version

v2.6.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 144.64 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/opt/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-28 | ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.6 => 0.68.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
